### ISSUE TITLE
MARVEL fails at hmmsearch step

### ISSUE THREAD

**Issue by Vini2** [LaboratorioBioinformatica/MARVEL#10]
I am trying to run MARVEL and it keeps failing at the `hmmsearch` step. 

Letting you know that I was able to fix it. In line 246 of `marvel_bins.py`, moving the the option `-Z 9518` before `<hmmfile>` and `<seqdb>` solved the issue.

Thanks!

**Comment by lbi-usp** [comment]
Thanks a lot for the fix.
