### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'results/prokka'

### ISSUE THREAD

**Issue by XiaomengWang0413** [LaboratorioBioinformatica/MARVEL#11]
I encountered this problem while using it
Traceback (most recent call last):
  File "marvel_bins.py", line 205, in <module>
    bin_dirs = os.listdir(prokka_results)
FileNotFoundError: [Errno 2] No such file or directory: 'results/prokka'
thanks

**Comment by jmartinsjrbr** [comment]
I've got the same error. 
I fixed it by replacing 'results/prokka' for 'prokka/ in line 246 of marvel_bins.py. Now the script creates the expected directory structure for output files

**Comment by jdeney** [comment]
Hello,
I noticed the issue you reported with the FileNotFoundError for the results/prokka directory. I've implemented a fix for this problem and have submitted a pull request to address it.
Please have a look at the pull request for the detailed changes, and once it's merged, the issue should be resolved.

**Comment by XiaomengWang0413** [comment]
Thanks



---Original---
From: "Deney ***@***.***&gt;
Date: Wed, Apr 17, 2024 22:08 PM
To: ***@***.***&gt;;
Cc: "Xiaomeng ***@***.******@***.***&gt;;
Subject: Re: [LaboratorioBioinformatica/MARVEL] FileNotFoundError: [Errno 2]No such file or directory: 'results/prokka' (Issue #11)




 
Hello,
 I noticed the issue you reported with the FileNotFoundError for the results/prokka directory. I've implemented a fix for this problem and have submitted a pull request to address it.
 Please have a look at the pull request for the detailed changes, and once it's merged, the issue should be resolved.

**Comment by lbi-usp** [comment]
merged pull request
