### ISSUE TITLE
Unable to run from other directories - Hard coded models

### ISSUE THREAD

**Issue by schackartk** [LaboratorioBioinformatica/MARVEL#7]
Hi! I am enjoying using your tool, but I have run into a problem.

I noticed that I cannot run MARVEL from directories other than this repository. 

For instance, trying to run from the parent directory:
```
$ ls
data/ MARVEL/

$ python3 MARVEL/marvel_bins.py -i data/bins_dir/
**Your database and models are not set. Please, run: python download_and_set_models.py
```

However, when running from this repository, it works:
```
$ ls
data/ MARVEL/

$ cd MARVEL

$ python3 marvel_bins.py -i ../data/bins_dir    # runs fine
```

This is because the path to the models is hard-coded in the script, first occuring on line 130:
```
if not os.path.isfile('models/all_vogs_hmm_profiles_feb2018.hmm'):
```

Most tools do not require the user to `cd` into the directory containing the script since it is restrictive. It would be more convenient to provide the models location as a command-line argument:
```
parser.add_argument(
    '-m',
    '--models',
    default='models/all_vogs_hmm_profiles_feb2018.hmm',
    help='HMM models file')

...

# Verify databases
if not os.path.isfile(args.models):
    parser.error(f'--models {args.models} does not exist. Please specify correct directory, or run python download_and_set_models.py if you have not already')
```

**Comment by BrunoKVI** [comment]
Thank you for the suggestion!
It was implemented.
