### ISSUE TITLE
Unable to control output directory

### ISSUE THREAD

**Issue by schackartk** [LaboratorioBioinformatica/MARVEL#8]
Hello!

Currently, the user cannot control where the output is written. This makes it inconvenient since I (and many others) like to organize using directories. As it is, my input directory (bin directory) gets cluttered with files from MARVEL.

It would be great to have a `-o|--outdir` argument, where the final output files are placed, with some generic default such as `out`. Ideally, intermediate files would be written to a temporary directory, or at least to `--outdir` and deleted upon completion.

If this gets implemented, it is also convenient to create the specified directory if it does not yet exist. _E.g._

```
if not os.path.isdir(args.outdir):
    os.makedirs(args.outdir)
```

**Comment by BrunoKVI** [comment]
Thank you for your suggestion. We added the argument -o --outdir to the script.
